export const MIGRATION_ORDER = [
  'migrate_warehouse_location.sql',
  'migrate_inbound_status.sql',
  'migrate_inbound_completed.sql',
  'migrate_logistics_receipt_qc.sql',
  'migrate_permissions.sql',
  'migrate_product_dev_sku.sql',
  'migrate_product_dev_fields.sql',
  'migrate_pre_purchase_order.sql',
  'migrate_purchase_actual.sql',
  'migrate_outbound.sql',
  'migrate_announcement_target.sql',
  'migrate_announcement_schedule.sql',
  'migrate_inbound_source_warehouse.sql',
  'migrate_drop_customer_credit_limit.sql',
  'migrate_inbound_arrival.sql',
  'migrate_takealot_store.sql',
  'migrate_outbound_fields.sql',
  'migrate_outbound_p1.sql',
  'migrate_outbound_p2.sql',
  'migrate_outbound_exception.sql',
  'migrate_outbound_sop_p0.sql',
  'migrate_sop_p1_print_billing.sql',
  'migrate_product_image.sql',
  'migrate_pricing_oms_flags.sql',
  'migrate_runtime_tables.sql',
  'migrate_operation_log.sql',
  'migrate_inbound_oms_customer.sql',
  'migrate_oms_portal_onboarding.sql',
  'migrate_return_order.sql',
  'migrate_return_receipt_phase1.sql',
  'migrate_return_attachment.sql',
  'migrate_return_warehouse.sql',
  'migrate_return_inspection_phase2.sql',
  'migrate_return_fee_template.sql',
  'migrate_return_warehouse_logistics.sql',
  'migrate_outbound_p3.sql',
  'migrate_outbound_takealot_meta.sql',
  'migrate_outbound_appointment_datetime.sql',
  'migrate_outbound_recipient.sql',
  'migrate_outbound_schema_sync.sql',
  'migrate_outbound_attachment_label_meta.sql',
  'migrate_schema_full_sync.sql',
] as const

/**
 * 一次性维护/数据修复脚本，不得由 migrate:all 自动执行。
 * 这些脚本可能重写业务编码或不是可重复的 schema migration，必须人工评审后运行。
 */
export const MANUAL_SQL_SCRIPTS = [
  'add_catalog_customer_tkl.sql',
  'add_product_measured_dims.sql',
  'add_supplier_freight_bill_po_link.sql',
  'migrate_customer_company_email.sql',
  'migrate_outbound_enhance.sql',
  'migrate_pre_purchase_confirmation.sql',
  'migrate_supplier_default_payment.sql',
  'rename_jhb_warehouse.sql',
] as const
