/**
 * Takealot Marketplace API 端点配置
 * 与 takealot-marketplace-api.openapi.json 保持同步
 */
window.TAKEALOT_API = {
  baseUrl: '/api/proxy',
  tags: [
    { id: 'General', label: '通用', icon: '⚙️' },
    { id: 'Offers', label: '商品报价', icon: '📦' },
    { id: 'Sales', label: '销售', icon: '💰' },
    { id: 'Transactions', label: '交易流水', icon: '💳' },
    { id: 'Shipments', label: '发货', icon: '🚚' },
    { id: 'Returns', label: '退货', icon: '↩️' },
    { id: 'Facilities', label: '仓储设施', icon: '🏭' },
    { id: 'Seller', label: '卖家', icon: '👤' },
  ],
  endpoints: [
  {
    id: 'status',
    tag: 'General',
    method: 'GET',
    path: '/status',
    summary: 'API 状态检查',
    description: '检查 API 是否在线。无需鉴权。',
    auth: false,
    params: [],
  },
  {
    id: 'offers-list',
    tag: 'Offers',
    method: 'GET',
    path: '/offers',
    summary: '获取报价列表',
    description: '分页查询报价。所有 Query 均为可选；不填则不传该参数。',
    auth: true,
    params: [
      { name: 'offer_id', in: 'query', type: 'number', label: '报价 ID' },
      { name: 'offer_id__in', in: 'query', type: 'text', label: '多个报价 ID', placeholder: '逗号分隔，如 123,456' },
      { name: 'status', in: 'query', type: 'select', label: '状态', options: ['', 'buyable', 'not_buyable', 'disabled_by_seller', 'disabled_by_takealot'] },
      { name: 'offer_id__gt', in: 'query', type: 'number', label: 'ID 大于' },
      { name: 'offer_id__lt', in: 'query', type: 'number', label: 'ID 小于' },
      { name: 'sku', in: 'query', type: 'text', label: 'SKU' },
      { name: 'barcode', in: 'query', type: 'text', label: '条形码' },
      { name: 'fields', in: 'query', type: 'text', label: '返回字段', placeholder: '逗号分隔' },
      { name: 'expands', in: 'query', type: 'text', label: '展开关联', placeholder: 'seller_warehouse_stock,offer_charges' },
      { name: 'limit', in: 'query', type: 'number', label: '每页数量', placeholder: '默认 100，最大 1000' },
      { name: 'continuation_token', in: 'query', type: 'text', label: '翻页令牌' },
      { name: 'order_by', in: 'query', type: 'select', label: '排序', options: ['', 'offer_id', '-offer_id'] },
      { name: 'include_count', in: 'query', type: 'select', label: '返回总数', options: ['', 'true', 'false'] },
    ],
  },
  {
    id: 'offers-create',
    tag: 'Offers',
    method: 'POST',
    path: '/offers',
    summary: '创建报价',
    description: '为 Takealot 目录中已存在的商品创建报价。barcode、sku 必填。',
    auth: true,
    params: [
      { name: 'fields', in: 'query', type: 'text', label: '返回字段' },
      { name: 'expands', in: 'query', type: 'text', label: '展开关联' },
    ],
    body: {
      required: ['barcode', 'sku'],
      example: {
        barcode: 'MPTALX12345678-9',
        sku: 'SKU-ABC123',
        minimum_leadtime_days: 5,
        selling_price: 345,
        rrp: 399,
        seller_warehouse_stock: [{ seller_warehouse_id: 1234, quantity_available: 100 }],
      },
    },
  },
  {
    id: 'offers-get-id',
    tag: 'Offers',
    method: 'GET',
    path: '/offers/{offer_id}',
    summary: '按 ID 获取报价',
    auth: true,
    params: [
      { name: 'offer_id', in: 'path', type: 'number', label: '报价 ID', required: true },
      { name: 'fields', in: 'query', type: 'text', label: '返回字段' },
      { name: 'expands', in: 'query', type: 'text', label: '展开关联' },
    ],
  },
  {
    id: 'offers-patch-id',
    tag: 'Offers',
    method: 'PATCH',
    path: '/offers/{offer_id}',
    summary: '按 ID 更新报价',
    auth: true,
    params: [
      { name: 'offer_id', in: 'path', type: 'number', label: '报价 ID', required: true },
    ],
    body: {
      example: {
        sku: 'SKU-ABC123',
        minimum_leadtime_days: 5,
        selling_price: 345,
        rrp: 399,
        seller_warehouse_stock: [{ seller_warehouse_id: 1234, quantity_available: 100 }],
      },
    },
  },
  {
    id: 'offers-get-sku',
    tag: 'Offers',
    method: 'GET',
    path: '/offers/by_sku/{sku}',
    summary: '按 SKU 获取报价',
    auth: true,
    params: [
      { name: 'sku', in: 'path', type: 'text', label: 'SKU', required: true },
      { name: 'fields', in: 'query', type: 'text', label: '返回字段' },
      { name: 'expands', in: 'query', type: 'text', label: '展开关联' },
    ],
  },
  {
    id: 'offers-patch-sku',
    tag: 'Offers',
    method: 'PATCH',
    path: '/offers/by_sku/{sku}',
    summary: '按 SKU 更新报价',
    auth: true,
    params: [
      { name: 'sku', in: 'path', type: 'text', label: 'SKU', required: true },
    ],
    body: {
      example: {
        selling_price: 345,
        rrp: 399,
        seller_warehouse_stock: [{ seller_warehouse_id: 1234, quantity_available: 100 }],
      },
    },
  },
  {
    id: 'offers-get-barcode',
    tag: 'Offers',
    method: 'GET',
    path: '/offers/by_barcode/{barcode}',
    summary: '按条形码获取报价',
    auth: true,
    params: [
      { name: 'barcode', in: 'path', type: 'text', label: '条形码', required: true },
      { name: 'fields', in: 'query', type: 'text', label: '返回字段' },
      { name: 'expands', in: 'query', type: 'text', label: '展开关联' },
    ],
  },
  {
    id: 'offers-patch-barcode',
    tag: 'Offers',
    method: 'PATCH',
    path: '/offers/by_barcode/{barcode}',
    summary: '按条形码更新报价',
    auth: true,
    params: [
      { name: 'barcode', in: 'path', type: 'text', label: '条形码', required: true },
    ],
    body: {
      example: {
        selling_price: 345,
        rrp: 399,
        seller_warehouse_stock: [{ seller_warehouse_id: 1234, quantity_available: 100 }],
      },
    },
  },
  {
    id: 'offers-batch-create',
    tag: 'Offers',
    method: 'POST',
    path: '/offers/batch',
    summary: '批量创建/更新报价',
    description: '单次最多 10000 条。offers 数组必填。',
    auth: true,
    params: [],
    body: {
      required: ['offers'],
      example: {
        offers: [
          {
            offer_id: 0,
            sku: 'SKU-ABC123',
            barcode: 'MPTALX12345678-9',
            selling_price: 345,
            rrp: 399,
            leadtime_days: 5,
            leadtime_stock: [{ merchant_warehouse_id: 1234, quantity: 100 }],
            status_action: 'Disable',
          },
        ],
      },
    },
  },
  {
    id: 'offers-batch-get',
    tag: 'Offers',
    method: 'GET',
    path: '/offers/batch/{batch_id}',
    summary: '按 ID 获取报价批次',
    auth: true,
    params: [
      { name: 'batch_id', in: 'path', type: 'number', label: '批次 ID', required: true },
    ],
  },
  {
    id: 'sales-list',
    tag: 'Sales',
    method: 'GET',
    path: '/sales',
    summary: '获取销售列表',
    description: '按日期查询时 gte/lte 成对使用，单次跨度不超过 180 天。',
    auth: true,
    params: [
      { name: 'order_id', in: 'query', type: 'number', label: '订单 ID' },
      { name: 'order_date__gte', in: 'query', type: 'date', label: '订单日期起' },
      { name: 'order_date__lte', in: 'query', type: 'date', label: '订单日期止' },
      { name: 'stock_source_region', in: 'query', type: 'select', label: '库存来源区域', options: ['', 'CPT', 'JHB', 'DBN', 'cpt', 'jhb', 'dbn'] },
      { name: 'limit', in: 'query', type: 'number', label: '每页数量', placeholder: '默认 20，最大 100' },
      { name: 'fields', in: 'query', type: 'text', label: '返回字段' },
      { name: 'continuation_token', in: 'query', type: 'text', label: '翻页令牌' },
      { name: 'include_count', in: 'query', type: 'select', label: '返回总数', options: ['', 'true', 'false'] },
    ],
  },
  {
    id: 'transactions-list',
    tag: 'Transactions',
    method: 'GET',
    path: '/transactions',
    summary: '获取交易列表',
    description: '默认最近 30 天，最大跨度 180 天。',
    auth: true,
    params: [
      { name: 'transaction_type__in', in: 'query', type: 'text', label: '交易类型', placeholder: 'charge-success-fee,payment-customer-order' },
      { name: 'created_at__gte', in: 'query', type: 'datetime-local', label: '起始时间' },
      { name: 'created_at__lte', in: 'query', type: 'datetime-local', label: '截止时间' },
      { name: 'limit', in: 'query', type: 'number', label: '每页数量' },
      { name: 'fields', in: 'query', type: 'text', label: '返回字段' },
      { name: 'expands', in: 'query', type: 'text', label: '展开 references' },
      { name: 'continuation_token', in: 'query', type: 'text', label: '翻页令牌' },
      { name: 'include_count', in: 'query', type: 'select', label: '返回总数', options: ['', 'true', 'false'] },
    ],
  },
  {
    id: 'balances',
    tag: 'Transactions',
    method: 'GET',
    path: '/balances',
    summary: '获取结算/可提现信息',
    auth: true,
    params: [],
  },
  {
    id: 'shipments-list',
    tag: 'Shipments',
    method: 'GET',
    path: '/shipments',
    summary: '获取发货列表',
    description: '只读接口，无法通过 API 创建发货单。',
    auth: true,
    params: [
      { name: 'shipment_id', in: 'query', type: 'number', label: '发货 ID' },
      { name: 'shipment_id__lt', in: 'query', type: 'number', label: 'ID 小于' },
      { name: 'shipment_id__gt', in: 'query', type: 'number', label: 'ID 大于' },
      { name: 'shipment_id__in', in: 'query', type: 'text', label: '多个发货 ID', placeholder: '逗号分隔' },
      { name: 'shipment_type__in', in: 'query', type: 'text', label: '发货类型', placeholder: 'customer_order,replenishment,mixed' },
      { name: 'shipped', in: 'query', type: 'select', label: '已发货', options: ['', 'true', 'false'] },
      { name: 'cancelled', in: 'query', type: 'select', label: '已取消', options: ['', 'true', 'false'] },
      { name: 'order_by', in: 'query', type: 'select', label: '排序', options: ['', 'shipment_id', '-shipment_id'] },
      { name: 'fields', in: 'query', type: 'text', label: '返回字段' },
      { name: 'expands', in: 'query', type: 'text', label: '展开 shipment_items' },
      { name: 'limit', in: 'query', type: 'number', label: '每页数量' },
      { name: 'include_count', in: 'query', type: 'select', label: '返回总数', options: ['', 'true', 'false'] },
      { name: 'continuation_token', in: 'query', type: 'text', label: '翻页令牌' },
    ],
  },
  {
    id: 'shipments-get',
    tag: 'Shipments',
    method: 'GET',
    path: '/shipments/{shipment_id}',
    summary: '获取单个发货',
    auth: true,
    params: [
      { name: 'shipment_id', in: 'path', type: 'number', label: '发货 ID', required: true },
      { name: 'fields', in: 'query', type: 'text', label: '返回字段' },
      { name: 'expands', in: 'query', type: 'text', label: '展开 shipment_items' },
    ],
  },
  {
    id: 'returns-list',
    tag: 'Returns',
    method: 'GET',
    path: '/returns',
    summary: '获取退货列表',
    auth: true,
    params: [
      { name: 'fields', in: 'query', type: 'text', label: '返回字段' },
      { name: 'expands', in: 'query', type: 'text', label: '展开 outcomes,transactions' },
      { name: 'return_reason__in', in: 'query', type: 'text', label: '退货原因', placeholder: 'defective_or_damaged,not_what_i_ordered' },
      { name: 'outcome__in', in: 'query', type: 'text', label: '处理结果', placeholder: 'sellable_stock,removal_order' },
      { name: 'return_region__in', in: 'query', type: 'text', label: '退货区域', placeholder: 'JHB,CPT' },
      { name: 'return_date__gte', in: 'query', type: 'date', label: '退货日期起' },
      { name: 'return_date__lte', in: 'query', type: 'date', label: '退货日期止' },
      { name: 'order_id', in: 'query', type: 'number', label: '订单 ID' },
      { name: 'return_reference_number', in: 'query', type: 'text', label: '退货参考号 RRN' },
      { name: 'sku', in: 'query', type: 'text', label: 'SKU' },
      { name: 'limit', in: 'query', type: 'number', label: '每页数量' },
      { name: 'continuation_token', in: 'query', type: 'text', label: '翻页令牌' },
      { name: 'order_by', in: 'query', type: 'select', label: '排序', options: ['', 'return_date', '-return_date'] },
      { name: 'include_count', in: 'query', type: 'select', label: '返回总数', options: ['', 'true', 'false'] },
    ],
  },
  {
    id: 'returns-get',
    tag: 'Returns',
    method: 'GET',
    path: '/returns/{return_id}',
    summary: '按 ID 获取退货',
    auth: true,
    params: [
      { name: 'return_id', in: 'path', type: 'number', label: '退货 ID', required: true },
      { name: 'fields', in: 'query', type: 'text', label: '返回字段' },
      { name: 'expands', in: 'query', type: 'text', label: '展开关联' },
    ],
  },
  {
    id: 'facilities-regions',
    tag: 'Facilities',
    method: 'GET',
    path: '/facilities/get_enabled_regions',
    summary: '获取已启用设施区域',
    auth: true,
    params: [],
  },
  {
    id: 'seller-info',
    tag: 'Seller',
    method: 'GET',
    path: '/seller',
    summary: '获取卖家信息',
    auth: true,
    params: [
      { name: 'fields', in: 'query', type: 'text', label: '返回字段' },
      { name: 'expands', in: 'query', type: 'text', label: '展开 warehouses,vacations' },
    ],
  },
  ],
};
