CREATE TABLE IF NOT EXISTS mingrui_shipment (
  id               BIGINT AUTO_INCREMENT PRIMARY KEY,
  shipment_no      VARCHAR(30)  NOT NULL,
  status           VARCHAR(30)  NOT NULL DEFAULT 'draft',
  mode             VARCHAR(10)  NOT NULL DEFAULT 'lcl',
  po_nos           VARCHAR(500) NULL,
  po_refs          JSON         NULL,
  inbound_no       VARCHAR(30)  NULL,
  dest_warehouse   VARCHAR(30)  NULL,
  origin_city      VARCHAR(50)  NULL,
  dest_port        VARCHAR(50)  NULL,
  packages         INT          NULL DEFAULT 0,
  weight_kg        DECIMAL(12,2) NULL,
  volume_cbm       DECIMAL(12,3) NULL,
  freight_amount   DECIMAL(14,2) NULL,
  etd              DATE         NULL,
  eta              DATE         NULL,
  vessel_name      VARCHAR(100) NULL,
  bl_no            VARCHAR(50)  NULL,
  container_no     VARCHAR(50)  NULL,
  mingrui_order_no VARCHAR(50)  NULL,
  tracking_status  VARCHAR(50)  NULL,
  tracking_detail  TEXT         NULL,
  cargo_items      JSON         NULL,
  api_status       VARCHAR(30)  NOT NULL DEFAULT 'not_configured',
  api_payload      JSON         NULL,
  last_sync_at     DATETIME(3)  NULL,
  last_sync_error  VARCHAR(500) NULL,
  remark           TEXT         NULL,
  created_by       BIGINT       NULL,
  created_at       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_mingrui_shipment_no (shipment_no),
  INDEX idx_mingrui_status (status),
  INDEX idx_mingrui_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='明瑞物流下单';
